apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersampleconfigdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Dockersampleconfig
  template:
    metadata:
      labels:
        app: Dockersampleconfig
    spec:
      containers:
      - name: cdxdockerrepos
        image: cdxsamplecr.azurecr.io/image5:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: dockersampleconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Dockersampleconfig
